apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookify-ingress
  namespace: bookify     # <--- REQUIRED
spec:
  ingressClassName: nginx
  rules:
    - host: bookify.local
      http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 8000

          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: accounts-service
                port:
                  number: 8000

          - path: /booking
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 8000

          - path: /restaurants
            pathType: Prefix
            backend:
              service:
                name: restaurants-service
                port:
                  number: 8000

          - path: /reviews
            pathType: Prefix
            backend:
              service:
                name: reviews-service
                port:
                  number: 8000

          - path: /search
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 8000
