apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-deployment
  namespace: bookify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurants-service
  template:
    metadata:
      labels:
        app: restaurants-service
    spec:
      containers:
        - name: restaurants-container
          image: bookify-restaurants-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bookify-secrets
                  key: DATABASE_URL
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bookify-secrets
                  key: DJANGO_SECRET_KEY

