apiVersion: v1
kind: Service
metadata:
  name: restaurants-service
  namespace: bookify
spec:
  type: NodePort
  selector:
    app: restaurants-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
