apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-deployment
  namespace: bookify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
        - name: reviews-container
          image: bookify-reviews:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bookify-secrets
                  key: DATABASE_URL
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bookify-secrets
                  key: DJANGO_SECRET_KEY
